version: '3'

services:
  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"

  db:
    restart: always
    image: postgres:14.7-alpine
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker

  celery:
    build: .
    tty: true
    command: celery -A config worker -l info
    env_file:
      - .env.docker
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l info
    env_file:
      - .env.docker
    depends_on:
      - redis
      - app
      - celery

volumes:
  pg_data: