# Generated by Django 5.0.4 on 2024-04-07 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiceHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Время начала выполнения')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('sign_nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('interval', models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_two_day', 'Один раз в 2 дня'), ('once_a_three_day', 'Один раз в 3 дня'), ('once_a_four_day', 'Один раз в 4 дня'), ('once_a_five_day', 'Один раз в 5 дней'), ('once_a_six_day', 'Один раз в 6 дней'), ('once_a_seven_day', 'Один раз в 7 дней')], default='once_a_day', max_length=100, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Награда')),
                ('duration_time', models.TimeField(verbose_name='Время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
                ('associated_nice_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nice_habit', to='habits.nicehabit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
